### ISSUE TITLE
Suggestions for CONTRIBUTING.md

### ISSUE THREAD

**Issue by tkruse** [ros/cmake_modules#2]
First off: I like this package.

The CMake recommendation link points to an ugly site. Using "blob_plain" helps:
http://cmake.org/gitweb?p=cmake.git;a=blob_plain;f=Modules/readme.txt

Also consider http://www.cmake.org/Wiki/CMake:How_To_Find_Libraries#Writing_find_modules
for friendlier entry point.

Also explain that cmake already ships with plenty Find...cmake files (avoid novice users contributing something that already exists), and point to their source.
Maybe point to other collections of cmakemodules like https://github.com/rpavlik/cmake-modules , http://code.google.com/p/mgep/source/browse/branches/clientv2/CMakeModules

If applicable, explain the requirements of catkin workspaces with respect to multiple calls to find_package() by different projects in the same cmake process, and the usage of cached vs. non-cached variables.

Also, you recommend using `<PackageName>_FOUND`, instead of `<PackageName_Uppercase>_FOUND` as set by FIND_PACKAGE_HANDLE_STANDARD_ARGS
Which implies you recommend using `<PackageName>_FOUND` in CMakeLists.txt files rather than `<PackageName_Uppercase>_FOUND`, which means you recommend against the CMake standards. Maybe give a justification of why people should avoid this standard. I am not saying the cmake standard is prettier and easier to learn and remember, I am just saying it is, well, standard. Also I am not sure whether macros reading ...-NOTFOUND expect all uppercase (or will in the future).

In your FindTinyXML.cmake code, you should IMO be more verbose with comments, what with people probably using it as a template for futher modules.
E.g. state why you set TinyXML_FOUND.
Maybe explain why you use TinyXML_LIBRARY before setting TinyXML_LIBRARIES? (E.g. for some reason avoid the API variables to be cached)?

**Comment by wjwwood** [comment]
@adolfo-rt

**Comment by wjwwood** [comment]
> The CMake recommendation link points to an ugly site. Using "blob_plain" helps:
> http://cmake.org/gitweb?p=cmake.git;a=blob_plain;f=Modules/readme.txt

We can use that one instead.

> Also consider http://www.cmake.org/Wiki/CMake:How_To_Find_Libraries#Writing_find_modules
> for friendlier entry point.

We can certainly include that one, but I found the other file more concise and better formatted, though it doesn't give as much general information as the one you pointed to. I think the current link is good for justifying the above style guidelines, but your link it better for general information and gives more concrete examples to people who actually are writing these modules.

> Also explain that cmake already ships with plenty Find...cmake files (avoid novice users contributing something that already exists), and point to their source.
> Maybe point to other collections of cmakemodules like https://github.com/rpavlik/cmake-modules, http://code.google.com/p/mgep/source/browse/branches/clientv2/CMakeModules

We can certainly be more explicit and gives some links, but I do already mention that CMake and other packages ship these modules too.

> If applicable, explain the requirements of catkin workspaces with respect to multiple calls to find_package() by different projects in the same cmake process, and the usage of cached vs. non-cached variables.

This might be applicable, but I'm not sure what we should say here.

> Also, you recommend using _FOUND, instead of _FOUND as set by FIND_PACKAGE_HANDLE_STANDARD_ARGS
> Which implies you recommend using _FOUND in CMakeLists.txt files rather than _FOUND, which means you recommend against the CMake standards. Maybe give a justification of why people should avoid this standard. I am not saying the cmake standard is prettier and easier to learn and remember, I am just saying it is, well, standard. Also I am not sure whether macros reading ...-NOTFOUND expect all uppercase (or will in the future).

The formatting didn't come through here for me, but I am assuming you are talking about `TINYXML_FOUND` vs `TinyXML_FOUND`?

I'm following this line:

> // From http://cmake.org/gitweb?p=cmake.git;a=blob_plain;f=Modules/readme.txt
> Xxx_FOUND               Set to false, or undefined, if we haven't found, or don't want to use Xxx.

Which seems to indicate to me that they would use the CamelCase or at least the exact same case as used in the file name. Though they do always return the uppercase from `find_package_handle_standard_args`. I see this as yet another case where CMake is inconsistent, so I made the `FindTinyXML.cmake` file provide both.

> In your FindTinyXML.cmake code, you should IMO be more verbose with comments, what with people probably using it as a template for futher modules.
> E.g. state why you set TinyXML_FOUND.
> Maybe explain why you use TinyXML_LIBRARY before setting TinyXML_LIBRARIES? (E.g. for some reason avoid the API variables to be cached)?

I can go back an mention why I do `set(TinyXML_FOUND ${TINYXML_FOUND})`.

@adolfo-rt, since you wrote it originally, do you care to expand on the comments and why you used `TinyXML_LIBRARY`, etc..?

**Comment by tkruse** [comment]
Fixed formatting.

Regarding Case of ...-FOUND, I see that you are right, ExactCase is the future. Discussed also here:
http://comments.gmane.org/gmane.comp.programming.tools.cmake.devel/6103
So the find_package_handle_standard_args will be extended. I cannot tell which version of cmake the change comes with, nor whether this will introduce USE_ORIGINAL_CASE, FPHSA_FOUND_VAR_OPTION, or even both :-( .

Close this issue now if you want.

**Comment by adolfo-rt** [comment]
There's an inconsistency indeed. On one hand the [readme](http://cmake.org/gitweb?p=cmake.git;a=blob_plain;f=Modules/readme.txt) recommends to preserve the script name capitalization in the variables, so `find_package(TinyXML)` should yield `TinyXML_FOUND`. On the other hand, the CMake-provided and highly recommended `find_package_handle_standard_args` yields an all-caps `TINYXML_FOUND`.

At the very least, we should make the whole set of exposed variables case-consistent, so this applies to `TinyXML_ROOT_DIR`, cache variables like `TinyXML_INCLUDE_DIR` and non-cache return variables like `TinyXML_INCLUDE_DIRS`. So if we go for case-preserving variables, doing `set(TinyXML_FOUND ${TINYXML_FOUND})` makes sense.

Concerning which case convention to use, I would favor the readme recommendation and not what `find_package_handle_standard_args` does. Readme quote:

_"We would like all FindXxx.cmake files to produce consistent variable names.
Please use the following consistent variable names for general use..."_

However, some examples from this [list](http://www.cmake.org/Wiki/CMake:Module_Maintainers) show that existing modules do not follow consistently this convention.
- `find_package(Boost)` yields `Boost_FOUND` **OK**
- `find_package(Bullet)` yields `BULLET_FOUND` **KO**
- `find_package(Doxygen)` yields `DOXYGEN_FOUND` **KO**
- `find_package(Protobuf)` yields `PROTOBUF_FOUND` **KO**
- `find_package(Qt4)` yields `QT_FOUND`, `Qt_FOUND` and `Qt4_FOUND` **OK**

Older scripts (written for CMake <=2.6) tend to be a capitalization mess because they were written at a time when there where no clear guidelines. The principle of least surprise does not seem to apply here, you'll pretty much always be surprized :_(

**Comment by tkruse** [comment]
That cmake Modules/readme.txt also has changed over time:
The Xxx notation was introduced in Mar 26 2013
http://www.cmake.org/pipermail/cmake-commits/2013-March/014773.html

`Using XXX as name of the package is ambiguous, since it can be
interpreted as "ALLUPPERCASE" and also as "ExactCase (if the name
is already ALLUPPERCASE)".
After extensive discussion there is the conclusion that ExactCase
is intended, so using a CamelCased name makes that more obvious.`

For what it's worth, the new readme.txt is not exactly better, since it
could mean CamelCase should be used even if original was all-upper :-( .
How hard can it be to just tell people to use ExactCase, I wonder.

Also note this discussion from 2010:
http://www.mail-archive.com/cmake-developers@cmake.org/msg00124.html
Sadly it took them 3 years to update readme.txt and FPHSA accordingly. I
believe it should be important not only to be consistent with all variable
names, but also make sure theother case vairable is _not also set_. meaning
it should be avoided where possible to introduce a script that sets both
TinyXML_FOUND and TINYXML_FOUND. Because cMakeLists.txt authors will of
course use both (not reading the docs), and if we later clean up the find
script, that would break CMakeLists.txt.

But then again, maybe I worry too much about this kind of thing.

**Comment by adolfo-rt** [comment]
> That cmake Modules/readme.txt also has changed over time: The Xxx notation was introduced in Mar 26 2013 http://www.cmake.org/pipermail/cmake-commits/2013-March/014773.html

<sighs> yes, it changed recently, and in the past 5 years I have written a very large amount of find scripts, all using upper case, following the previous recommendations.

> How hard can it be to just tell people to use ExactCase, I wonder.

Me too...

> ...it should be avoided where possible to introduce a script that sets both TinyXML_FOUND and TINYXML_FOUND. Because cMakeLists.txt authors will of course use both (not reading the docs), and if we later clean up the find script, that would break CMakeLists.txt. But then again, maybe I worry too much about this kind of thing.

We can always unset the ALL_CAPS variable.

We'd have to check hoy FPHSA behaves in the minimum CMake version required by Hydro, and take it from there.

**Comment by wjwwood** [comment]
Because of constant surprise, I think the best thing we can do is to enforce usage documentation and get users in the habit of looking at the file's documentation before assuming how to use it.

Inevitably, I always end up reading the `FindXxx.cmake` file I am using in order to discover the real variable names I should be using.

**Comment by wjwwood** [comment]
https://github.com/ros/cmake_modules/pull/3

**Comment by wjwwood** [comment]
I believe I touched on everything mentioned by @tkruse, except for:

> If applicable, explain the requirements of catkin workspaces with respect to multiple calls to find_package() by different projects in the same cmake process, and the usage of cached vs. non-cached variables.

I don't really know what to say about that, I guess the TinyXML example touches on this with the `TinyXML_LIBRARY` variable and comments.

**Comment by tkruse** [comment]
Fair enough. Probably cmake find modules should be written to make it possible to call them more than once in any case. It is just as well to wait and see what people write, and extend the rules based on any detected bugs.
