### ISSUE TITLE
Eigen deprecation should be added to jade migration

### ISSUE THREAD

**Issue by mikeferguson** [ros/cmake_modules#35]
I don't know all the details of this deprecation, but just saw it for the first time, we should probably note this on the Jade migration guide (http://wiki.ros.org/jade/Migration). @wjwwood looks like you committed the deprecation notice, perhaps you can fill this in with some background?

**Comment by wjwwood** [comment]
Yeah, I don't even remember doing this :smile:, but it was the result of this conversation:

https://github.com/ros/cmake_modules/issues/25

Basically there has been a Module provided by Eigen for a while now and we'd like to eventually get everyone using the one they provide if possible. Which is the stated long term goal of Modules in this package:

https://github.com/ros/cmake_modules/blob/0.4-devel/CONTRIBUTING.md#long-term-contribution

I'll add a note to the Jade migration guide which states the deprecation has occurred and that we may remove the module from this package in K-turtle.

**Comment by wjwwood** [comment]
I've updated the Jade's Migration page on the wiki:

http://wiki.ros.org/jade/Migration#Eigen_CMake_Module_in_cmake_modules

**Comment by mikeferguson** [comment]
@wjwwood thanks!

**Comment by meyerj** [comment]
There is an issue with the cmake snippet in the jade migration guide:

The `FindEigen3.cmake` module provided by Eigen itself sets the `EIGEN3_INCLUDE_DIR` variable, not `EIGEN3_INCLUDE_DIRS` (at least for libeigen3-dev version 3.2.0-8 in Ubuntu trusty). I therefore propose to update the migration guide like this:

```
find_package(Eigen3)
if(NOT EIGEN3_FOUND)
  # Fallback to cmake_modules
  find_package(cmake_modules REQUIRED)
  find_package(Eigen REQUIRED)
  set(EIGEN3_FOUND ${EIGEN_FOUND})
  set(EIGEN3_INCLUDE_DIR ${EIGEN_INCLUDE_DIRS})
  set(EIGEN3_LIBRARIES ${EIGEN_LIBRARIES})  # <-- not required as Eigen is header only
  # Possibly map additional variables to the EIGEN3_ prefix.
endif()
# Use ${EIGEN3_INCLUDE_DIR} and other ${EIGEN3_...} variables in either case below
```

But this solution does not work anymore with `catkin_package(DEPENDS EIGEN3)` to export the dependency to other packages (if Eigen is used in public headers), because catkin only looks for the `*_FOUND`, `*_INCLUDE_DIRS` and `*_LIBRARIES` suffixes. Instead, `${EIGEN3_INCLUDE_DIR}` has to be added to the `catkin_package(INCLUDE_DIRS ...)` list or the cmake snippet must be adapted like:

```
find_package(Eigen3)
if(NOT EIGEN3_FOUND)
  # Fallback to cmake_modules
  find_package(cmake_modules REQUIRED)
  find_package(Eigen REQUIRED)
  set(EIGEN3_FOUND ${EIGEN_FOUND})
  set(EIGEN3_INCLUDE_DIRS ${EIGEN_INCLUDE_DIRS})
  set(EIGEN3_LIBRARIES ${EIGEN_LIBRARIES})  # <-- not required as Eigen is header only
  # Possibly map additional variables to the EIGEN3_ prefix.
else()
  set(EIGEN3_INCLUDE_DIRS ${EIGEN3_INCLUDE_DIR})
endif()
# Use ${EIGEN3_...} variables in either case below
```

Note that `EIGEN3_FOUND` should also be set in both cases and is required for `catkin_package(DEPENDS EIGEN3)`.

**Comment by wjwwood** [comment]
@meyerj unfortunately I believe that passing `EIGEN3` to `catkin_package(DEPENDS ...)` will not work because what I think happens is that when some other package find's the package which depends on `EIGEN3`, the other package will also try to `find_package(EIGEN3)` and look for common suffixes like `_INCLUDE_DIRS`, so it will also miss the `EIGEN3_INCLUDE_DIR`.

I think the correct action here is to advise people to pass along Eigen stuff through `catkin_package` without using the `DEPENDS` option. I'd also continue to pass along the `EIGEN3_LIBRARIES` option even if it's empty for now. The reason being that even header only packages may need to export a link flag on something like `dl` or `pthread`, so better safe than sorry. But I'll put a note on there about that anyways.

I've updated the wiki slightly to reflect your suggestions:

http://wiki.ros.org/action/diff/jade/Migration?action=diff&rev1=5&rev2=6

**Comment by TeamHectorDarmstadt** [comment]
> @meyerj unfortunately I believe that passing EIGEN3 to catkin_package(DEPENDS ...) will not work because what I think happens is that when some other package find's the package which depends on EIGEN3, the other package will also try to find_package(EIGEN3) and look for common suffixes like _INCLUDE_DIRS, so it will also miss the EIGEN3_INCLUDE_DIR.

catkin already resolves the `<prefix>_INCLUDE_DIRS` and `<prefix>_LIBRARIES` in the `catkin_package()` call itself. Other than for catkin dependencies they are simply added after all include directories and libraries specified in the `INCLUDE_DIRS` and `LIBRARIES` arguments (see [catkin_package.xml:133ff.](https://github.com/ros/catkin/blob/de8053f85adeb1900b29a5e88b9d326422982b46/cmake/catkin_package.cmake#L133)). That's also how it is documented in the file's header and Eigen is the example use case there.

But I agree that adding the Eigen headers to the `INCLUDE_DIRS` alone is the simpler solution for a header only dependency and would not require the definition of the `EIGEN3_INCLUDE_DIRS` (with the final S) variable in the else branch.

**Comment by meyerj** [comment]
> @meyerj unfortunately I believe that passing EIGEN3 to catkin_package(DEPENDS ...) will not work because what I think happens is that when some other package find's the package which depends on EIGEN3, the other package will also try to find_package(EIGEN3) and look for common suffixes like _INCLUDE_DIRS, so it will also miss the EIGEN3_INCLUDE_DIR.

catkin already resolves the `<prefix>_INCLUDE_DIRS` and `<prefix>_LIBRARIES` in the `catkin_package()` call itself. Other than for catkin dependencies they are simply added after all include directories and libraries specified in the `INCLUDE_DIRS` and `LIBRARIES` arguments (see [catkin_package.xml:133ff.](https://github.com/ros/catkin/blob/de8053f85adeb1900b29a5e88b9d326422982b46/cmake/catkin_package.cmake#L133)). That's also how it is documented in the file's header and Eigen is the example use case there.

But I agree that adding the Eigen headers to the `INCLUDE_DIRS` alone is the simpler solution for a header only dependency and would not require the definition of the `EIGEN3_INCLUDE_DIRS` (with the final S) variable in the else branch.

**Comment by wjwwood** [comment]
You're right. At some point I think we changed how that works (or maybe that's only true for catkin depends). Either way I agree advising people to just pass the headers along with `INCLUDE_DIRS` in their `catkin_package` call is sufficient.
